sudo: false
language: go
go:
  - 1.5
  - tip
services:
  - postgresql

env:
  - ENV=travis
before_script:
  - go vet github.com/ihsw/go-home/app/...
script:
  - go test github.com/ihsw/go-home/app/...
