base:
  image: ihsw/go-home
web-test:
  extends:
    service: base
web:
  extends:
    service: base
  ports:
    - 80:80
test:
  extends:
    service: base
  command: go test github.com/ihsw/go-home/app/...
